global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'quarkus'
    scrape_interval: 5s
    metrics_path: /q/metrics
    static_configs:
      - targets: ['docker.for.mac.localhost:8080']

  - job_name: 'quarkus-mutiny'
    scrape_interval: 5s
    metrics_path: /q/metrics
    static_configs:
      - targets: ['docker.for.mac.localhost:8081']
